version: '3.8'

services:
  portfolio-frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: portfolio-frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:3001
      - VITE_LLM_ENABLED=false
    networks:
      - portfolio-network
    depends_on:
      - portfolio-server
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
