version: '3.8'

services:
  # Production portfolio service
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        # Proxy settings auto-detected from environment
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1,.local}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge