

services:
  # Production service - ready for ECS/Cloud Run
  portfolio-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
    profiles:
      - production

  # Development service (simplified - use local `npm run dev` for development)
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:5173"
    environment:
      - NODE_ENV=development
    profiles:
      - dev
