

services:
  # Development service
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:5173"
    volumes:
      - .:/app
      - portfolio_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - portfolio-network

  # Production service
  portfolio-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network
    profiles:
      - production

networks:
  portfolio-network:
    driver: bridge

volumes:
  portfolio_node_modules:
