# Staging environment values
replicaCount: 2

image:
  repository: padmanaban-portfolio
  tag: "staging"
  pullPolicy: Always

resources:
  limits:
    cpu: 150m
    memory: 192Mi
  requests:
    cpu: 75m
    memory: 96Mi

service:
  type: LoadBalancer

env:
  NODE_ENV: staging

config:
  NODE_ENV: "staging"
  DEBUG: "false"

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: true
  minAvailable: 1

ingress:
  enabled: true
  hosts:
    - host: staging-portfolio.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: staging-portfolio-tls
      hosts:
        - staging-portfolio.local