# Production environment values
replicaCount: 3

image:
  repository: padmanaban-portfolio
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: LoadBalancer

env:
  NODE_ENV: production

config:
  NODE_ENV: "production"
  DEBUG: "false"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 2

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: padmanaban-portfolio.com  # Replace with your domain
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: portfolio-prod-tls
      hosts:
        - padmanaban-portfolio.com

networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
    - from: []
